#!/usr/bin/env ansible-playbook

# Title         : apt.yml
# Description   : Update the inventory servers thanks to apt or another equivalent module, as well as other independent programs
# Author        : Veltys
# Date          : 2022-12-26
# Version       : 1.1.2
# Usage         : sh apt.yml | bash apt.yml | ./apt.yml
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: Ansible upgrader
  hosts: all
  become: true

  tasks:
    - name: Ansible apt update && apt upgrade for Debian-based distros
      block:

      - name: Ansible apt update && apt upgrade
        register: updatesys
        ansible.builtin.apt:
          name: "*"
          state: latest
          update_cache: yes

      - name: Display the last line of the apt task if not changed
        ansible.builtin.debug:
          msg: "{{updatesys.stdout_lines|last}}"
        when: not(updatesys.changed)

      - name: Display all the lines of the apt task if changed
        ansible.builtin.debug:
          msg: "{{updatesys.stdout_lines}}"
        when: updatesys.changed

      - name: Autoremove no longer required packages
        ansible.builtin.apt:
          autoremove: true

      when: (ansible_facts.distribution == 'Ubuntu') or
            (ansible_facts.distribution == 'Debian')


    - name: Netdata updater for Heracles
      block:

      - name: Netdata updater
        register: updatend
        ansible.builtin.shell: "/usr/libexec/netdata/netdata-updater.sh"

      - name: Display the last line of the Netdata task if not changed
        ansible.builtin.debug:
          msg: "{{updatend.stdout_lines|last}}"
        when: not(updatend.changed)

      - name: Display all the lines of the Netdata task if changed
        ansible.builtin.debug:
          msg: "{{updatend.stdout_lines}}"
        when: updatend.changed

      when: (ansible_facts.architecture == 'armv6l')


    - name: Old ansible upgrader (opkg) for OpenSPA
      block:

      - name: Old ansible updater (opkg)
        ansible.builtin.shell: "opkg update"

      - name: Old ansible upgrader (opkg)
        register: updatesys
        ansible.builtin.shell: "opkg upgrade"

      - name: Display the last line of the previous task if not empty
        ansible.builtin.debug:
          msg: "{{updatesys.stdout_lines}}"
        when: updatesys.stdout_lines | length > 0

      when: not(
              (ansible_facts.distribution == 'Ubuntu') or
              (ansible_facts.distribution == 'Debian')
            )