#!/usr/bin/env ansible-playbook

# Title         : netdata.yml
# Description   : Upgrades netdata service in servers which cannot be installed as a package
# Author        : Veltys
# Date          : 2023-02-09
# Version       : 1.0.0
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Netdata upgrader'
  register: updatend
  ansible.builtin.shell:
    cmd: 'tmux new-session ''/usr/libexec/netdata/netdata-updater.sh'''

- name: 'Display all the lines of the Netdata task if changed'
  ansible.builtin.debug:
    msg: "{{ updatend.stdout_lines }}"
  when: updatend.changed
