#!/usr/bin/env ansible-playbook

# Title         : updater.yml
# Description   : Updates the inventory servers thanks to apt or another equivalent module, as well as other independent programs
# Author        : Veltys
# Date          : 2023-02-09
# Version       : 2.0.0
# Usage         : ansible-playbook updater.yml | sh updater.yml | bash updater.yml | ./updater.yml
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Ansible upgrader'
  hosts: all
  become: true

  tasks:
    - name: 'Updater and upgrader for Debian based distros'
      tags:
        - apt
        - update
        - upgrade
      ansible.builtin.import_tasks: apt.yml
      when:
        ansible_facts.distribution == 'Ubuntu' or
        ansible_facts.distribution == 'Debian'

    - name: 'Updater and upgrader for Red Hat based distros'
      tags:
        - yum
        - update
        - upgrade
      ansible.builtin.import_tasks: yum.yml
      when:
        ansible_facts.distribution == 'Red Hat' or
        ansible_facts.distribution == 'CentOS'

    - name: 'Updater and upgrader for SUSE based distros'
      tags:
        - zypper
        - update
        - upgrade
      ansible.builtin.import_tasks: zypper.yml
      when:
        "'SUSE' in ansible_facts['distribution'] | upper()"

    - name: 'Netdata upgrader for Heracles'
      tags:
      - netdata
      - upgrade
      ansible.builtin.import_tasks: netdata.yml
      when: ansible_facts.architecture == 'armv6l'

    - name: 'Old ansible upgrader (opkg) for OpenSPA'
      tags:
      - opkg
      - update
      - upgrade
      ansible.builtin.import_tasks: opkg.yml
      when:
          ansible_facts.distribution != 'Ubuntu' and
          ansible_facts.distribution != 'Debian' and
          ansible_facts.distribution != 'Red Hat' and
          ansible_facts.distribution != 'CentOS' and
          "'SUSE' in ansible_facts['distribution'] | upper()"
