# Title         : tester.yml
# Description   : Configures GitHub Actions to perform integration tests
# Author        : Veltys
# Date          : 2022-12-27
# Version       : 1.3.0
# Usage         : (used externally)
# Notes         : 


name: Testing Action

on: 
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: "Decrypt"
        shell: bash
        env:
          PASSPHRASE:		${{ secrets.PASSPHRASE }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output inventory.yml inventory.yml.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output private_key.pem private_key.pem.gpg

      - name: "Test"
        shell: bash
        env:
          PASSPHRASE:		${{ secrets.PASSPHRASE }}
        run: |
          ansible-playbook --private-key private_key.pem -i inventory.yml apt.yml
