# Title         : tester.yml
# Description   : Configures GitHub Actions to perform integration tests
# Author        : Veltys
# Date          : 2022-12-27
# Version       : 1.3.1
# Usage         : (used externally)
# Notes         : 


name: Testing Action

on: 
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: "Decrypt"
        shell: bash
        env:
          PASSPHRASE:		${{ secrets.PASSPHRASE }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output inventory.yml inventory.yml.gpg
          mkdir ~/.ssh
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output ~/.ssh/id_rsa private_key.pem.gpg
          chmod 600 ~/.ssh/id_rsa

      - name: "Test"
        shell: bash
        run: |
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook --skip-tags netdata -i inventory.yml apt.yml

      - name: "Clean"
        shell: bash
        run: |
          rm ~/.ssh/id_rsa

